yaml
   name: Flutter CI

   on:
     push:
       branches:
         - main
     pull_request:
       branches:
         - main

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up Flutter
         uses: subosito/flutter-action@v2
         with:
           flutter-version: 'stable'  # veya istediğiniz bir versiyonu belirtebilirsiniz

       - name: Install dependencies
         run: flutter pub get

       - name: Run Flutter build
         run: flutter build apk  # veya başka bir komut (flutter build ios gibi)

       - name: Run tests
         run: flutter test
   
