name: Deploy GitHub Pages

on:
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # Setup Flutter instead of Dart
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.19.3"

      - name: Clean project
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - run: flutter --version

      # Build web release
      - name: Build Web Release
        run: flutter build web --release

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b gh-pages
          cp -r build/web/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -u origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
